- 
  hosts: all
  sudo: true
  vars_files:
          - vars.yml
          - secret.yml
  tasks:
        - name: Install ssh server and git 
          apt: name={{ item }} state=installed #update-cache=yes
          with_items: "{{ system_packages }}"

        - name: Create git user
          user: name={{ git_user }} home=/home/{{ git_user }}

        - name: Create directories
          file: path={{ item }} state=directory mode=700 owner={{ git_user }}
          with_items:
                  - "{{ bin }}/static"
                  - "{{ git_root }}"

        - name: Copy executable files
          copy: src={{ lookup('env', 'GOPATH') }}/bin/{{ item }} dest={{ bin }} mode=755 owner={{ git_user }}
          with_items:
                  - gorlim_web
                  - gorlim_github
                  - gorlim_ssh
                  - gorlim_hooks


        - name: Check .ssh
          file: path=/home/{{ git_user }}/.ssh state=directory owner={{ git_user }} mode=700

        - name: Check authorized_keys
          file: path=/home/{{ git_user }}/.ssh/authorized_keys state=touch owner={{ git_user }} mode=700

        - include: tasks/web.yml

        - include: tasks/github.yml

        - include: tasks/rsyslog.yml
